USE SMS
CREATE TABLE Parent
(
  Id INT NOT NULL,
  FirstName VARCHAR(100) NOT NULL,
  FathersName VARCHAR(100) NOT NULL,
  GrandFathersName VARCHAR(100) NOT NULL,
  Gender VARCHAR(6) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Phone VARCHAR(20) NOT NULL,
  DateOfBirth DATE NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE Subject
(
  Id INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE Grade
(
  Id INT NOT NULL,
  Value INT NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE Section
(
  Id INT NOT NULL,
  Value VARCHAR(6) NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE Teacher
(
  Id INT NOT NULL,
  FirstName VARCHAR(100) NOT NULL,
  FathersName VARCHAR(100) NOT NULL,
  GrandFathersName VARCHAR(100) NOT NULL,
  Gender VARCHAR(6) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Phone VARCHAR(20) NOT NULL,
  DateOfBirth DATE NOT NULL,
  SubjectId INT NOT NULL,
  PRIMARY KEY (Id),
  FOREIGN KEY (SubjectId) REFERENCES Subject(Id)
);

CREATE TABLE OfficeStaff
(
  Id INT NOT NULL,
  FirstName VARCHAR(100) NOT NULL,
  FathersName VARCHAR(100) NOT NULL,
  GrandFathersName VARCHAR(100) NOT NULL,
  Gender VARCHAR(6) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Phone VARCHAR(20) NOT NULL,
  DateOfBirth DATE NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE Announcement
(
  Id INT NOT NULL,
  Title VARCHAR(100) NOT NULL,
  Detail VARCHAR(250) NOT NULL,
  OfficeStaffId INT NOT NULL,
  PRIMARY KEY (Id),
  FOREIGN KEY (OfficeStaffId) REFERENCES OfficeStaff(Id)
);

CREATE TABLE SubjectForGrade
(
  Id INT NOT NULL,
  SubjectId INT NOT NULL,
  GradeId INT NOT NULL,
  PRIMARY KEY (Id),
  FOREIGN KEY (SubjectId) REFERENCES Subject(Id),
  FOREIGN KEY (GradeId) REFERENCES Grade(Id)
);

CREATE TABLE Class
(
  Id INT NOT NULL,
  SectionId INT NOT NULL,
  GradeId INT NOT NULL,
  HomeroomId INT NOT NULL,
  PRIMARY KEY (Id),
  FOREIGN KEY (SectionId) REFERENCES Section(Id),
  FOREIGN KEY (GradeId) REFERENCES Grade(Id),
  FOREIGN KEY (HomeroomId) REFERENCES Teacher(Id)
);

CREATE TABLE Student
(
  Id INT NOT NULL,
  FirstName VARCHAR(100) NOT NULL,
  FathersName VARCHAR(100) NOT NULL,
  GrandFathersName VARCHAR(100) NOT NULL,
  Gender VARCHAR(6) NOT NULL,
  Phone VARCHAR(20) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  DateOfBirth DATE NOT NULL,
  ParentId INT NOT NULL,
  ClassId INT NOT NULL,
  PRIMARY KEY (Id),
  FOREIGN KEY (ParentId) REFERENCES Parent(Id),
  FOREIGN KEY (ClassId) REFERENCES Class(Id)
);

CREATE TABLE Appointment
(
  Id INT NOT NULL,
  AppointmentDate DATE NOT NULL,
  Detail VARCHAR(250) NOT NULL,
  OfficeStaffId INT NOT NULL,
  StudentId INT NOT NULL,
  PRIMARY KEY (Id),
  FOREIGN KEY (OfficeStaffId) REFERENCES OfficeStaff(Id),
  FOREIGN KEY (StudentId) REFERENCES Student(Id)
);

CREATE TABLE Assessment
(
  Id INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  OutOf INT NOT NULL,
  Score FLOAT NOT NULL,
  StudentId INT NOT NULL,
  SubjectId INT NOT NULL,
  PRIMARY KEY (Id),
  FOREIGN KEY (StudentId) REFERENCES Student(Id),
  FOREIGN KEY (SubjectId) REFERENCES Subject(Id)
);

CREATE TABLE AttendanceMissed
(
  Id INT NOT NULL,
  Period VARCHAR(50) NOT NULL,
  SubjectName VARCHAR(100) NOT NULL,
  Date DATE NOT NULL,
  StudentId INT NOT NULL,
  PRIMARY KEY (Id),
  FOREIGN KEY (StudentId) REFERENCES Student(Id)
);